spring:
  resources:
    static-locations: classpath:/dist/
  thymeleaf:
    prefix: classpath:/dist/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: orange
    url: jdbc:mysql://localhost:3306/replace_dbname?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    sql-script-encoding: UTF-8
#    initialization-mode: ALWAYS
#    data: classpath:TestData.sql
  session:
    cookie:
      samesite: LAX
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
#     ddl-auto: update
#     generate-ddl: create
      dialect: org.hibernate.dialect.MySQL5Dialect
      use-new-id-generator-mappings: true
      show-sql: true

  logging:
    level:
      org:
        hibernate: debug
server:
  servlet:
    session:
      cookie:
        secure: true
      samesite:
        security: LAX
#    oauth2:
#      client:
#        registration:
#          twitter:
#            client-id: 【client-id】
#            client-secret: 【client-secret】
#            scope:
#              - email
#              - public_profile
#            redirect-uri: 【アプリケーションのURL】/login/oauth2/code/{registrationId}
#        provider:
#    user:
#      name: user01
#      password: password